### DISCUSSION TITLE
도커 컴포즈 yml

### DISCUSSION THREAD

**Discussion by yybmion** [yybmion/yumcup#21] [General]
```yml
version: '3.8'

services:
  blue:
    image: {도커허브유저네임}/live_server:latest
    container_name: blue
    ports:
      - "8080:8080"
    environment:
      - PROFILES=blue
      - ENV=blue
    volumes:
      - /home/ubuntu/config:/config
```
(그린도 위에 방식으로 같게 작성)

볼륨은 ec2에서 민감한 정보에 대해 config의 secret.yml에 담아두었는데 그 설정파일도 포함한다.
