### DISCUSSION TITLE
깃허브 액션 (CICD), 도커 파일

### DISCUSSION THREAD

**Discussion by yybmion** [yybmion/yumcup#22] [General]
```yml
name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean bootJar -x test       (Gradle과 Maven에 맞게 작성)

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker
        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/live_server .
      - name: Push Docker
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/live_server:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set target IP
        run: |
          STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.LIVE_SERVER_IP }}/env")
          echo $STATUS
          if [ $STATUS = 200 ]; then
            CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.LIVE_SERVER_IP }}/env")
          else
            CURRENT_UPSTREAM=green
          fi
          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
          if [ $CURRENT_UPSTREAM = blue ]; then
            echo "CURRENT_PORT=8080" >> $GITHUB_ENV
            echo "STOPPED_PORT=8081" >> $GITHUB_ENV
            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
          elif [ $CURRENT_UPSTREAM = green ]; then
            echo "CURRENT_PORT=8081" >> $GITHUB_ENV
            echo "STOPPED_PORT=8080" >> $GITHUB_ENV
            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
          else
            echo "error"
            exit 1
          fi

      - name: Docker compose
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.LIVE_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/live_server:latest
            sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d

      - name: Check deploy server URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://${{ secrets.LIVE_SERVER_IP }}:${{env.STOPPED_PORT}}/env
          max-attempts: 5
          retry-delay: 10s

      - name: Change nginx upstream
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.LIVE_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo docker exec -i nginxserver bash -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/conf.d/service-env.inc && nginx -s reload' 

      - name: Stop current server
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.LIVE_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if docker ps -a | grep -q ${{env.CURRENT_UPSTREAM}}; then
              sudo docker stop ${{env.CURRENT_UPSTREAM}} || true
              sudo docker rm ${{env.CURRENT_UPSTREAM}} || true
            fi
```

```yml
FROM amazoncorretto:21-alpine-jdk

ARG JAR_FILE=build/libs/yumcup.jar
ARG PROFILES
ARG ENV

COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java", "-Dspring.profiles.active=${PROFILES}", "-Dserver.env=${ENV}", "-Dspring.config.additional-location=/config/", "-jar", "app.jar"]
```

이후 왜 도커 파일을 저렇게 설정했는지 나옴!. (secret.yml 에 중요한 정보 모두 저장했는데 그걸 환경변수로 넣어주는거임) -> 환경변수 안 넣어주면 빌드 과정에서 오류남

전체적인 과정은 다음과 같음!

1. Dockerfile 빌드 시점:
```dockerfile
FROM amazoncorretto:21-alpine-jdk
ARG JAR_FILE=build/libs/yumcup.jar
ARG PROFILES
ARG ENV
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-Dspring.profiles.active=${PROFILES}", "-Dserver.env=${ENV}", "-jar", "app.jar"]
```
- JAR 파일을 이미지에 복사
- 실행 명령어 정의
- 이 시점에서는 실제 환경변수 값이 주입되지 않음

2. docker-compose-green.yml 실행 시점:
```yaml
version: '3.8'

services:
  blue:
    image: {도커허브유저네임}/live_server:latest
    container_name: blue
    ports:
      - "8080:8080"
    environment:
      - PROFILES=blue
      - ENV=blue
    volumes:
      - /home/ubuntu/config:/config
```
- 미리 빌드된 이미지 사용
- 컨테이너 실행 시 환경변수 주입
- 포트 매핑 설정

실제 실행 순서:
```
1. GitHub Actions:
   - Dockerfile로 이미지 빌드
   - Docker Hub에 이미지 푸시

2. EC2 서버:
   - docker-compose로 이미지 pull
   - compose 파일의 환경변수를 컨테이너에 주입하며 실행
   - 애플리케이션이 환경변수를 읽어서 사용
```

따라서, Dockerfile에서는 환경변수를 받을 수 있는 구조만 정의하고, 실제 값은 docker-compose 실행 시점에 주입된다. 이렇게 하면 같은 이미지로 다양한 환경에서 다른 설정값으로 실행할 수 있다.

그래서 secret.yml에 env에 저장해놓은 민감한 정보들을 compose파일의 환경변수를 컨테이너에 주입한다는데 그게 `볼륨`에 정의되어있음!! (EC2에 실제 값이 포함된 application-secret.yml 생성)

1. Jar파일 생성하는 부분에서 내 프로젝트는 frontend와 backend가 모두 있으니 주의해서 백엔드만 jar 생성시키자.
2. 빌드 명령어 './gradlew clean bootJar -x test' (민약 그냥 로컬에서 빌드해보고싶다면)

___

! 주의해야할 점들
1. secret 설정을 할 수 있는데 민감한 정보는 넣어준다! (깃허브에 있음) Setting -> Secret and Variables
2. Dockerfile이다!! CamelCase로 작성하지 말아라!!
3. ec2 인바운드 규칙에 포트 모두 열어주자 8080,8081
4. 해당 깃허브액션 작성을 하고 나서 맨 처음 `Check deploy server URL` 에서 계속해서 실패하여 고생을 함
5. 에러의 핵심은 Redis 연결 설정에서 발생! 
6. 따라서 SECRET.YML에 REDIS관련 환경변수도 추가해줌 (REDIS는 EC2내에 설치해줌!) -> https://dangdangee.tistory.com/entry/Redis-ec2%EC%97%90-%EB%A0%88%EB%94%94%EC%8A%A4-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0 (Ec2에 Redis설치 방법 사이트)
7. 중요!! Redis-server setup을 해야한다!!!!!!!!!!
8. (참고 사이트) https://wookgu.tistory.com/26   ,   https://hokyun1.tistory.com/192
9. ElasticCache를 사용하는 방법도 있음. AWS 기능중 하나
10. 똑같이 Mysql도 설정안해주면 에러 나니 설치해주는데 이번에는 RDS 사용함. (환경변수도 설정!)
11. `jdbc:mysql://{RDS-ENDPOINT}:3306/yumcup` -> RDS사용하려면 secret.yml 다음과 같은 형식임.
12. RDS 설정하고 3306도 보안그룹 추가. (https://king-ja.tistory.com/105)
13. RDS 접속 `mysql -h [RDS-엔드포인트] -u root -p`
14. jpa 설정에서 ddl-auto: update로 되어있다면, 애플리케이션 실행 시 Entity 클래스들을 기반으로 테이블이 자동으로 생성!
15. RDS 생성할떄의 username과 password도 secret에 넣어줘야함!!
16. 도커파일의 "-Dspring.config.additional-location=/config/" 이 옵션은 yml에서 읽는 설정파일이 충돌하고 있어서 넣어줌!(local과 secret 환경변수 겹침)
17. application.yml의 데이터베이스 설정(환경변수 사용)이 application-secret.yml의 실제 RDS 접속 정보로 덮어써진다는 의미!
18.  대부분 이정도면 깃허브 액션 설정하고 push했을때 정상동작할것이다!
